---
- name: Escuchar eventos de webhook y ejecutar un playbook (desde Git)
  hosts: localhost

  sources:
    - name: Escuchar en un webhook en el puerto 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Reaccionar cuando el mensaje es 'accion_requerida'
      condition: event.payload.message is defined and event.payload.message == "accion_requerida"
      action:
        run_playbook:
          # Usamos una ruta explícita relativa a la raíz del proyecto
          name: "{{ ansible_rulebook.project_dir }}/saludo_webhook_playbook.yml"
          inventory: "{{ ansible_rulebook.project_dir }}/inventory.yml" 
          # ↑↑↑ CORRECCIÓN CLAVE ↑↑↑
