---
- name: Escuchar eventos de webhook y ejecutar un playbook
  hosts: localhost
  gather_facts: false

  sources:
    - name: Escuchar en un webhook en el puerto 5001
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Reaccionar cuando el mensaje es 'accion_requerida'
      condition: event.payload.message is defined
      action:
        debug:

